# GitHub Actions Workflow for Automatic Deployment
# Save this as .github/workflows/deploy.yml in your repository

name: Deploy to DigitalOcean

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy to DigitalOcean
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.DROPLET_IP }}
        username: root
        key: ${{ secrets.DROPLET_SSH_KEY }}
        script: |
          cd /var/www/partner-management
          sudo -u partnerapp git pull origin main
          sudo -u partnerapp npm ci --production
          sudo -u partnerapp npm run build
          sudo -u partnerapp npm run db:push
          sudo -u partnerapp pm2 reload partner-app --update-env
          
          # Health check
          sleep 5
          if curl -f http://localhost:3000/api/init > /dev/null 2>&1; then
            echo "✅ Deployment successful!"
          else
            echo "❌ Deployment failed - health check failed"
            exit 1
          fi